name: Terraform EKS with Karpenter

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Environment to deploy
        required: true
        options: [dev, staging, prod]
      action:
        type: choice
        description: Terraform action
        required: true
        options: [plan, apply, destroy]
        default: plan
      stage:
        type: choice
        description: Deployment stage
        required: true
        options: [eks-iam, karpenter, full]
        default: full

env:
  TF_VERSION: 1.6.0

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Select Workspace
      run: |
        terraform workspace select ${{ github.event.inputs.environment }} || \
        terraform workspace new ${{ github.event.inputs.environment }}

    - name: Terraform Validate
      run: terraform validate

    - name: Determine deployment targets
      id: targets
      run: |
        if [ "${{ github.event.inputs.stage }}" = "eks-iam" ]; then
          echo "TARGETS=-target=module.eks -target=module.iam" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.inputs.stage }}" = "karpenter" ]; then
          echo "TARGETS=-target=module.karpenter" >> $GITHUB_OUTPUT
        else
          echo "TARGETS=" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Plan
      if: github.event.inputs.action == 'plan'
      run: |
        if [ -n "${{ steps.targets.outputs.TARGETS }}" ]; then
          terraform plan ${{ steps.targets.outputs.TARGETS }} \
            -var-file="environments/${{ github.event.inputs.environment }}.tfvars" \
            -out=tfplan
        else
          terraform plan \
            -var-file="environments/${{ github.event.inputs.environment }}.tfvars" \
            -out=tfplan
        fi
        
        # 保存 plan 输出供后续步骤使用
        terraform show -no-color tfplan > plan_output.txt

    - name: Upload Terraform Plan
      if: github.event.inputs.action == 'plan'
      uses: actions/upload-artifact@v4
      with:
        name: terraform-plan-${{ github.event.inputs.environment }}-${{ github.event.inputs.stage }}
        path: |
          tfplan
          plan_output.txt

    - name: Deploy EKS and IAM
      if: github.event.inputs.action == 'apply' && (github.event.inputs.stage == 'eks-iam' || github.event.inputs.stage == 'full')
      run: |
        terraform apply -auto-approve \
          -target=module.eks \
          -target=module.iam \
          -var-file="environments/${{ github.event.inputs.environment }}.tfvars"

    - name: Wait for EKS Cluster
      if: github.event.inputs.action == 'apply' && github.event.inputs.stage == 'full'
      run: |
        CLUSTER_NAME=$(terraform output -raw cluster_name)
        echo "Waiting for cluster $CLUSTER_NAME to become active..."
        for i in {1..30}; do
          STATUS=$(aws eks describe-cluster --name $CLUSTER_NAME --query 'cluster.status' --output text 2>/dev/null || echo "CREATING")
          if [ "$STATUS" = "ACTIVE" ]; then
            echo "Cluster is ACTIVE"
            break
          fi
          echo "Cluster status: $STATUS (attempt $i/30)"
          sleep 30
        done
        if [ "$STATUS" != "ACTIVE" ]; then
          echo "Cluster did not become active in time"
          exit 1
        fi

    - name: Deploy Karpenter
      if: github.event.inputs.action == 'apply' && (github.event.inputs.stage == 'karpenter' || github.event.inputs.stage == 'full')
      run: |
        terraform apply -auto-approve \
          -target=module.karpenter \
          -var-file="environments/${{ github.event.inputs.environment }}.tfvars"

    - name: Apply from Plan
      if: github.event.inputs.action == 'apply' && github.event.inputs.stage == 'full'
      run: |
        # 如果有 plan 文件，使用它来 apply
        if [ -f "tfplan" ]; then
          terraform apply -auto-approve tfplan
        else
          terraform apply -auto-approve -var-file="environments/${{ github.event.inputs.environment }}.tfvars"
        fi

    - name: Destroy Karpenter
      if: github.event.inputs.action == 'destroy' && (github.event.inputs.stage == 'karpenter' || github.event.inputs.stage == 'full')
      run: |
        terraform destroy -auto-approve \
          -target=module.karpenter \
          -var-file="environments/${{ github.event.inputs.environment }}.tfvars"

    - name: Destroy EKS and IAM
      if: github.event.inputs.action == 'destroy' && (github.event.inputs.stage == 'eks-iam' || github.event.inputs.stage == 'full')
      run: |
        terraform destroy -auto-approve \
          -target=module.eks \
          -target=module.iam \
          -var-file="environments/${{ github.event.inputs.environment }}.tfvars"

    - name: Plan Destroy
      if: github.event.inputs.action == 'plan' && github.event.inputs.stage == 'full'
      run: |
        terraform plan -destroy \
          -var-file="environments/${{ github.event.inputs.environment }}.tfvars" \
          -out=tfdestroyplan
        
        terraform show -no-color tfdestroyplan > destroy_plan_output.txt

    - name: Upload Destroy Plan
      if: github.event.inputs.action == 'plan' && github.event.inputs.stage == 'full'
      uses: actions/upload-artifact@v4
      with:
        name: terraform-destroy-plan-${{ github.event.inputs.environment }}
        path: |
          tfdestroyplan
          destroy_plan_output.txt

    - name: Complete Terraform Destroy
      if: github.event.inputs.action == 'destroy' && github.event.inputs.stage == 'full'
      run: |
        terraform destroy -auto-approve -var-file="environments/${{ github.event.inputs.environment }}.tfvars"